# Generated by Django 4.2.1 on 2023-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
