# Generated by Django 4.2.3 on 2023-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('order placed', 'order placed'), ('out for delivery', 'out for delivery'), ('cancelled', 'cancelled'), ('shipped', 'shipped')], default='Order Placed', max_length=100),
        ),
    ]
